BEGIN;

CREATE TABLE IF NOT EXISTS produtos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  "desc" TEXT,
  preco NUMERIC(10,2) NOT NULL DEFAULT 0,
  estoque INTEGER NOT NULL DEFAULT 0,
  imagem TEXT,
  emoji VARCHAR(10) DEFAULT '🍨',
  ordem INTEGER DEFAULT 0,
  criado TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO produtos (id, nome, "desc", preco, estoque, emoji) VALUES
  (1, 'DinDin Ninho com Nutella', 'Super cremoso, feito com leite Ninho verdadeiro e muita Nutella.', 4.50, 10, '🍫'),
  (2, 'DinDin Morango Sensação', 'Aquele sabor de morango cremoso com casquinha de chocolate crocante.', 4.00, 8, '🍓'),
  (3, 'DinDin Paçoca Cremosa', 'Feito com amendoim selecionado, sabor marcante e delicioso.', 3.50, 5, '🥜'),
  (4, 'Bolo de Pote Cenoura', 'Massa fofinha de cenoura com cobertura generosa de brigadeiro.', 8.00, 4, '🍰'),
  (5, 'Bolo de Pote Prestígio', 'Bolo de chocolate molhadinho com recheio cremoso de coco.', 8.00, 3, '🥥'),
  (6, 'Bolo de Pote Red Velvet', 'Massa vermelha aveludada com recheio de cream cheese doce.', 10.00, 0, '🧁')
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('produtos', 'id'), COALESCE((SELECT MAX(id) FROM produtos), 1), true);

CREATE TABLE IF NOT EXISTS config (
  chave VARCHAR(100) PRIMARY KEY,
  valor TEXT,
  atualizado TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO config (chave, valor) VALUES
  ('pix', '{"tipo":"Telefone","chave":"(61) 99279-6430","nome":"ReinoGourmet"}'),
  ('contato', '{"tipo":"whatsapp","whatsapp":"5561992796430","msgWpp":"Olá! Quero fazer um pedido.","iframe":"","email":"yanpietro0101@gmail.com","assunto":"Pedido DinDin"}'),
  ('logo_header', ''),
  ('logo_sobre', ''),
  ('carrossel', '{"ativo":false,"eyebrow":"Destaques","titulo":"Em Destaque","slides":[]}')
ON CONFLICT (chave) DO NOTHING;

CREATE TABLE IF NOT EXISTS pedidos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  contato VARCHAR(255),
  contato_tipo VARCHAR(50),
  itens TEXT,
  total NUMERIC(10,2),
  status VARCHAR(20) DEFAULT 'pendente'
    CHECK (status IN ('pendente', 'confirmado', 'entregue', 'cancelado')),
  criado TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS slides (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo VARCHAR(255) NOT NULL,
  "desc" TEXT,
  preco NUMERIC(10,2),
  imagem TEXT,
  emoji VARCHAR(10),
  ordem INTEGER DEFAULT 0
);

COMMIT;
